### ISSUE TITLE
document Act supported versions

### ISSUE THREAD

**Issue by Ginxo** [kiegroup/mock-github#40]
I would recommend to add documentation about the Act supported versions since code like https://github.com/kiegroup/mock-github/blob/41a529b13e91245472239a3a4e315361f2437b3c/src/act/act.ts#L54 would eventually fail depending on the version.
 I would also recommend to add act_version matrix for https://github.com/kiegroup/mock-github/blob/41a529b13e91245472239a3a4e315361f2437b3c/.github/workflows/pull_request.yml#L16 this way we will assure the tool will still working for supported ones

**Comment by shubhbapna** [comment]
I haven't tested with older version, so for now I guess I can put latest version.

For `act_version` matrix I am not sure if that is possible. If you take a look at the action i am using to [setup act](https://github.com/shubhbapna/setup-act/blob/main/action.yml#L17) it uses their install script and it doesn't look like I can specify the version number for to their script.

**Comment by shubhbapna** [comment]
Not relevent anymore. Check  https://github.com/kiegroup/act-js
