### ISSUE TITLE
differenciate between integration and unitary tests

### ISSUE THREAD

**Issue by Ginxo** [kiegroup/mock-github#43]
the idea is to be able to run unitary or integration tests since we are mixing them and it takes too long to check whether all tests are passing or not.

this guide can be followed https://medium.com/coding-stones/separating-unit-and-integration-tests-in-jest-f6dd301f399c and I would use `.test.ts` and `.it.ts` suffixes to differentiate them

This is a integration test case https://github.com/kiegroup/mock-github/blob/main/test/act/act.test.ts where act is not mocked
This is a unitary test case https://github.com/kiegroup/mock-github/blob/main/test/github/github.test.ts since third-party or additional libraries are mocked

**Comment by shubhbapna** [comment]
By mocking act you mean mock the `spawn` call where we actually call the act cli tool?

**Comment by Ginxo** [comment]
> By mocking act you mean mock the `spawn` call where we actually call the act cli tool?

my mistake for act case, mockapi.test is a right example @shubhbapna

**Comment by shubhbapna** [comment]
So for `Act` and `ActionCompiler` we really can't change anything right?
For `MockGithub` we have already implemented this.
So this will just impact `Moctokit` and `Mockapi` correct?

**Comment by shubhbapna** [comment]
Not relevant as of now since `Act`, `Mockapi` and `ActionCompiler` were removed
