### ISSUE TITLE
extract act tool to npm library

### ISSUE THREAD

**Issue by Ginxo** [kiegroup/mock-github#45]
I would suggest to extract just act tool as an npm library itself. For that I would suggest to keep it as simple as possible for now and refactor mock-github on a multipackage project, one for core one for act (I would name it something like `act-js` or `act-node`) and one for shared (we will think about externalizing them all in the future). 
I would suggest to move to pnpm for easy multipackage handling...
wdyt @shubhbapna ?

I also recommend to move https://github.com/shubhbapna/setup-act as an additional package

**Comment by shubhbapna** [comment]
I feel like instead of having a multipackage project in a single repo, it might be easier to maintain both as separate projects cause both are pretty huge. So managing issues, PRs would be simpler no?

**Comment by shubhbapna** [comment]
Made a wrapper for `act-js` - https://github.com/shubhbapna/act-js

**Comment by shubhbapna** [comment]
resolved by [kiegroup/act-js](https://github.com/kiegroup/act-js)
